### ISSUE TITLE
iOS 5 - Transition became weird and rude

### ISSUE THREAD

**Issue by odanu** [thefaj/OpenFlow#21]
Hi, 
It seems that Apple has made some changes related to transformations and positioning. I have discovered that when I run OpenFlow on iOS 5 device/simulatore, the transition from one cover to another became ugly and weird.

**Comment by idevsoftware** [comment]
http://stackoverflow.com/questions/7686506/how-can-i-make-openflow-work-correctly-in-ios-5-0/7788434#7788434

**Comment by odanu** [comment]
My solution for this issue includes this code replacement for transformations init:

```
leftTransform = CATransform3DTranslate(CATransform3DIdentity, 0, 0, SIDE_COVER_ZPOSITION);
leftTransform = CATransform3DRotate(leftTransform, SIDE_COVER_ANGLE, 0.0f, 1.0f, 0.0f);
rightTransform = CATransform3DTranslate(CATransform3DIdentity, 0, 0, SIDE_COVER_ZPOSITION);
rightTransform = CATransform3DRotate(rightTransform, SIDE_COVER_ANGLE, 0.0f, -1.0f, 0.0f);
```
