### ISSUE TITLE
iPad Implementation

### ISSUE THREAD

**Issue by ghost** [thefaj/OpenFlow#7]
I've successfully added an AFOpenFlowView as a subview of my main view using the initWithFrame method. Once I place the view where I would like it on the screen (at the bottom), however, it no longer receives any touch information or moves the covers. Any ideas what could be causing this problem? Any help would be much appreciated.

**Comment by jkap** [comment]
Post your code so that I can take a look at it. I have an iPad implementation as well, and your problem sounds like one I initially had, but my code is <i>very</i> dependent on it's positioning.

**Comment by ghost** [comment]
I've solved this problem, I forgot to come back and close this once I had. Thanks for reaching out.

**Comment by cielojr** [comment]
same problem i had, but I was able to fix it by commenting this line //self.layer.position=CGPointMake(self.frame.size.width / 2, self.frame.size.height / 2);
so i wonder maybe i've destroyed something, but as i've tested it, its working fine... and a lot interactive now.
